version: '3.4'

networks:
  common:
    attachable: true
    driver: 'overlay'
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  email-password-site:
    image: "octoblu/login-ui:latest"
    env_file: "./env.d/email-password-site.env"
    networks:
      common:
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: continue
        monitor: 1m
      labels:
        - traefik.frontend.rule=HostRegexp:email-password-site,email-password-site.{domain:[a-zA-Z0-9.]+}
        - traefik.port=80
  meshblu-authenticator-email-password:
    image: "octoblu/meshblu-authenticator-email-password:latest"
    env_file: "./env.d/meshblu-authenticator-email-password.env"
    networks:
      common:
    depends_on:
      - meshblu-core-protocol-adapter-http
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: continue
        monitor: 1m
      labels:
        - traefik.frontend.rule=HostRegexp:email-password,email-password.{domain:[a-zA-Z0-9.]+}
        - traefik.port=80
volumes:
  dependencies:
    labels:
      - './meshblu-http.yml'
      - './traefik.yml'
