version: '3.4'

networks:
  common:
    driver: 'overlay'
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  nanocyte-engine-http:
    image: "octoblu/nanocyte-engine-http:latest"
    env_file: "./env.d/nanocyte-engine-http.env"
    networks:
      common:
    depends_on:
      - meshblu-core-protocol-adapter-http
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: rollback
        monitor: 1m
      labels:
        - traefik.frontend.rule=HostRegexp:nanocyte-engine.localhost
        - traefik.frontend.entryPoints=http
        - traefik.port=80
  nanocyte-engine-worker:
    image: "octoblu/nanocyte-engine-worker"
    env_file: "./env.d/nanocyte-engine-worker.env"
    networks:
      common:
    depends_on:
      - meshblu-core-protocol-adapter-http
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: rollback
        monitor: 1m
  nanocyte-flow-deploy-service:
    image: "octoblu/nanocyte-flow-deploy-service:latest"
    env_file: "./env.d/nanocyte-flow-deploy-service.env"
    networks:
      common:
    depends_on:
      - meshblu-core-protocol-adapter-http
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: rollback
        monitor: 1m
      labels:
        - traefik.frontend.rule=HostRegexp:nanocyte-flow-deploy.localhost
        - traefik.frontend.entryPoints=http
        - traefik.port=80

volumes:
  dependencies:
    labels:
      - './traefik.yml'
