version: '3.4'

services:
  meshblu-core-firehose-socket-io:
    image: "octoblu/meshblu-core-firehose-socket.io:latest"
    env_file: "./env.d/meshblu-core-firehose-socket-io.env"
    depends_on:
      - meshblu-core-protocol-adapter-http
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: rollback
        monitor: 1m

volumes:
  dependencies:
    labels:
      - './meshblu-http.yml'
