version: '3.4'

services:
  meshblu-core-dispatcher:
    image: "octoblu/meshblu-core-dispatcher:latest"
    env_file: "./env.d/meshblu-core-dispatcher.env"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: rollback
        monitor: 1m
  meshblu-core-worker-webhook:
    image: "octoblu/meshblu-core-worker-webhook:latest"
    env_file: "./env.d/meshblu-core-worker-webhook.env"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: rollback
        monitor: 1m
