version: '3.4'

networks:
  common:
    attachable: true
    driver: 'overlay'
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  mongo:
    image: mongo
    networks:
      common:
    deploy:
      resources:
        limits:
          memory: 100M
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
