version: '3.4'

networks:
  common:

services:
  mongo:
    image: mongo
    networks:
      - common
    deploy:
      resources:
        limits:
          memory: 100M
    volumes:
      - ./data/mongo-data:/data/db
