version: '3.4'

networks:
  common:
    attachable: true
    driver: 'overlay'
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  api-octoblu:
    image: "octoblu/api-octoblu:latest"
    env_file: "./env.d/api-octoblu.env"
    networks:
      common:
    depends_on:
      - meshblu-core-protocol-adapter-http
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: continue
        monitor: 1m
      labels:
        - traefik.frontend.rule=HostRegexp:api-octoblu,api-octoblu.{domain:[a-zA-Z0-9.]+}
        - traefik.port=80
  app-api-octoblu:
    image: 'octoblu/nginx-dumb-proxy:latest'
    env_file: './env.d/app-api-octoblu.env'
    networks:
      common:
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: continue
        monitor: 1m
      labels:
        - traefik.frontend.rule=HostRegexp:app-octoblu,app-octoblu.{domain:[a-zA-Z0-9.]+};PathPrefix:/api
        - traefik.port=80
  app-octoblu:
    image: "octoblu/app-octoblu:latest"
    env_file: "./env.d/app-octoblu.env"
    networks:
      common:
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: continue
        monitor: 1m
      labels:
        - traefik.frontend.rule=HostRegexp:app-octoblu,app-octoblu.{domain:[a-zA-Z0-9.]+}
        - traefik.port=80

volumes:
  dependencies:
    labels:
      - './authenticators.yml'
      - './flows.yml'
      - './meshblu-http.yml'
      - './meshblu-firehose-socket-io.yml'
      - './traefik.yml'
