version: '3.4'

networks:
  common:
    attachable: true
    driver: 'overlay'
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  traefik:
    command: >
      traefik
        --docker
        --docker.swarmmode
        --docker.watch
        --web
        --defaultEntryPoints=http,ws
    env_file: "./env.d/traefik.env"
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 30s
        max_attempts: 5
        window: 120s
      update_config:
        delay: 30s
        failure_action: continue
        monitor: 1m
    image: traefik:v1.4
    networks:
      common:
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme-storage:/acme

volumes:
  acme-storage:
